[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"
