backend:
  name: github
  repo: ronanmcgee/loukeman
  branch: main
  auth_type: implicit
  app_id: 80879

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "dates"
    label: "Dates"
    folder: "content/dates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
