backend:
  name: github
  repo: yourusername/loukeman
  branch: main
  base_url: https://yoursite.netlify.app
  auth_endpoint: /.netlify/functions/auth

site_url: https://yoursite.netlify.app

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "dates"
    label: "Tour Dates"
    folder: "data/dates"
    create: true
    format: "json"
    fields:
      - { name: "date", label: "Date", widget: "datetime", format: "YYYY-MM-DD" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "venue", label: "Venue", widget: "string" }
      - { name: "tickets", label: "Ticket URL", widget: "string", required: false }
