backend:
  name: github
  repo: yourusername/loukeman.com
  branch: main
  base_url: https://loukeman.com
  auth_endpoint: /api/auth

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "dates"
    label: "Tour Dates"
    folder: "data/dates"
    create: true
    format: "json"
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "venue", label: "Venue", widget: "string" }
      - { name: "tickets", label: "Ticket URL", widget: "string", required: false }
